---
- name: This sets up an httpd webserver
  hosts: all
  become: yes
  tasks:
  - name: Delete existing httpd
    yum:
      name: httpd
      state: absent
    tags: remove
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
    tags: get
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
    tags: start
